# The name of the application (no spaces)
app_name: skeletal_fragments

# A brief description of the app.
description : Find all the proper nouns which have adjectives modifying them. Dump the nouns and the adjectives into a text file.

# Your first and last name
user: Edward Chen

# Your email
email: edwardchen2003@gmail.com

# The primary language the application is written in - will be used for installing dependencies
# Current options are Python, R, and Go
language: R

# You can choose to specify a list of dictionaries, a list of terms, or both.
# If both dictionaries and terms are provided, all terms in the dictionary PLUS
# all listed terms will be used

terms: [skeletal, fossil, shell]
